# 远程配置文件，用于动态调整部分配置

# 新增的服务器IP列表
server_ip_list = []

# 是否启用卡密界面
enable_card_secret = true
# 是否启用直接购买界面
enable_pay_directly = true
# 是否优先展示卡密界面（设置为false时则优先显示直接购买界面）
show_card_secret_first = false

# 是否显示支付宝红包图片
enable_alipay_redpacket = true

# 新增的黑名单
[[black_list]]
# 封禁于
ban_at = "2022-07-19"
# QQ
qq = "787146611"
# 昵称
nickname = "Always  miss"
# 原因
reason = "不会配置道聚城的手游，退款"
